project_id = "mcbnenmqnxdqfcfiofka"

[functions.file-api]
verify_jwt = false

[functions.public-file]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-summarize]
verify_jwt = false
